[project]
name = "project-euler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nicolas Chareyre", email = "nicolas.chareyre@insee.fr" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
project-euler = "project_euler:main"

[build-system]
requires = ["uv_build>=0.10.3,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "black>=26.1.0",
    "pytest>=9.0.2",
]
